name: Python CI

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04 # https://github.com/actions/runner-images#available-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Python and Poetry
        uses: ./.github/actions/linux
        with:
          python-version: '3.11'

      - name: Lint with mypy and flake8
        env:
          FINGERPRINT_KEY: ${{ secrets.FINGERPRINT_KEY }}
          BRIGHTDATA_USERNAME: ${{ secrets.BRIGHTDATA_USERNAME }}
          BRIGHTDATA_PASSWORD: ${{ secrets.BRIGHTDATA_PASSWORD }}
        run: |
          mkdir ./dist && touch ./dist/README.md
          poetry run mypy pybas_automation/ tests/
          poetry run flake8 pybas_automation/ tests/

  test:
    needs: [ lint ]
    runs-on: ubuntu-22.04 # https://github.com/actions/runner-images#available-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Python and Poetry
        uses: ./.github/actions/linux
        with:
          python-version: '3.11'

      - name: Run tests with pytest
        env:
          FINGERPRINT_KEY: ${{ secrets.FINGERPRINT_KEY }}
          BRIGHTDATA_USERNAME: ${{ secrets.BRIGHTDATA_USERNAME }}
          BRIGHTDATA_PASSWORD: ${{ secrets.BRIGHTDATA_PASSWORD }}
        run: |
          mkdir ./dist && touch ./dist/README.md
          mkdir -p ./coverage/lcov/functional
          poetry run pytest -vv --cov=pybas_automation --cov-report=lcov:coverage/lcov/functional/coverage.lcov tests/functional

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        # https://github.com/codecov/codecov-action#arguments
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: tests_functional
          files: coverage/lcov/functional/coverage.lcov
          fail_ci_if_error: false

  poetry_build:
    needs: [ lint, test ]
    runs-on: ubuntu-22.04 # https://github.com/actions/runner-images#available-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Python and Poetry
        uses: ./.github/actions/linux
        with:
          python-version: '3.11'

      - name: Build python package with poetry
        run: |
          mkdir ./dist && touch ./dist/README.md
          poetry check
          poetry run python scripts/update_readme_links.py
          poetry build
